"""add constraints

Revision ID: 0b600b809076
Revises: 87107bc26b6d
Create Date: 2025-10-11 10:24:48.894411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b600b809076"
down_revision: Union[str, Sequence[str], None] = "87107bc26b6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_title", "snippets", ["user_id", "title"]
    )
    op.create_unique_constraint(
        "uq_snippet_tag", "snippets_tags", ["snippet_id", "tag_id"]
    )
    op.alter_column(
        "tags",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "tags", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")
    op.alter_column(
        "tags",
        "name",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_constraint("uq_snippet_tag", "snippets_tags", type_="unique")
    op.drop_constraint("uq_user_title", "snippets", type_="unique")
    # ### end Alembic commands ###
