"""add username field, rename password field

Revision ID: a12133574c7a
Revises: 67d78f23fa61
Create Date: 2025-09-23 22:33:11.334118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a12133574c7a"
down_revision: Union[str, Sequence[str], None] = "67d78f23fa61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.String(length=40), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
    )
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "_hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "_hashed_password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
